### ISSUE TITLE
demo error

### ISSUE THREAD

**Issue by melih1996** [ZhengyiLuo/MEVA#3]
Hi when I run the command python scripts/run_meva_on_video.py --cfg train_meva_2  --vid_file zen_talking_phone.mp4  --output_folder results/output --exp train_meva_2 I get the error below:

/home/melih/Desktop/virtualTry/MEVA/meva/utils/transformations.py:1927: UserWarning: No module named 'meva.utils._transformations'
  warnings.warn(str(err))
Running "ffmpeg -i zen_talking_phone.mp4 -f image2 -v error /tmp/zen_talking_phone_mp4/%06d.png"
Images saved to "/tmp/zen_talking_phone_mp4"
Input video number of frames 901
Running Multi-Person-Tracker
100%|███████████████████████████████████████████| 76/76 [01:06<00:00,  1.15it/s]
Finished. Detection + Tracking FPS 13.63
loading VAErecV2 model from checkpoint: results/meva/vae_rec_2/models/model_1000.p
Loaded pretrained weights from "results/meva/train_meva_2/model_best.pth.tar"
Running MEVA on each tracklet...
100%|█████████████████████████████████████████████| 1/1 [00:53<00:00, 54.00s/it]
VIBE FPS: 16.69
Total time spent: 125.86 seconds (including model loading time).
Total FPS (including model loading time): 7.16.
Saving output results to "results/output/zen_talking_phone/vibe_output.pkl".
Rendering output video, writing frames to /tmp/zen_talking_phone_mp4_output
  0%|                                                   | 0/901 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/melih/anaconda3/envs/pose/lib/python3.6/site-packages/OpenGL/latebind.py", line 41, in __call__
    return self._finalCall( *args, **named )
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/run_meva_on_video.py", line 334, in <module>
    main(args)
  File "scripts/run_meva_on_video.py", line 260, in main
    mesh_filename=mesh_filename,
  File "/home/melih/Desktop/virtualTry/MEVA/meva/utils/renderer.py", line 105, in render
    rgb, _ = self.renderer.render(self.scene, flags=render_flags)
  File "/home/melih/anaconda3/envs/pose/lib/python3.6/site-packages/pyrender/offscreen.py", line 102, in render
    retval = self._renderer.render(scene, flags, seg_node_map)
  File "/home/melih/anaconda3/envs/pose/lib/python3.6/site-packages/pyrender/renderer.py", line 125, in render
    self._update_context(scene, flags)
  File "/home/melih/anaconda3/envs/pose/lib/python3.6/site-packages/pyrender/renderer.py", line 737, in _update_context
    p._add_to_context()
  File "/home/melih/anaconda3/envs/pose/lib/python3.6/site-packages/pyrender/primitive.py", line 324, in _add_to_context
    self._vaid = glGenVertexArrays(1)
  File "/home/melih/anaconda3/envs/pose/lib/python3.6/site-packages/OpenGL/latebind.py", line 45, in __call__
    return self._finalCall( *args, **named )
  File "/home/melih/anaconda3/envs/pose/lib/python3.6/site-packages/OpenGL/wrapper.py", line 657, in wrapperCall
    result = wrappedOperation( *cArguments )
  File "/home/melih/anaconda3/envs/pose/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 401, in __call__
    if self.load():
  File "/home/melih/anaconda3/envs/pose/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 390, in load
    error_checker = self.error_checker,
  File "/home/melih/anaconda3/envs/pose/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 148, in constructFunction
    if (not is_core) and not self.checkExtension( extension ):
  File "/home/melih/anaconda3/envs/pose/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 270, in checkExtension
    result = extensions.ExtensionQuerier.hasExtension( name )
  File "/home/melih/anaconda3/envs/pose/lib/python3.6/site-packages/OpenGL/extensions.py", line 98, in hasExtension
    result = registered( specifier )
  File "/home/melih/anaconda3/envs/pose/lib/python3.6/site-packages/OpenGL/extensions.py", line 105, in __call__
    if not specifier.startswith( self.prefix ):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str

**Comment by ZhengyiLuo** [comment]
Looks like the inference code did run but it failed during rendering. The estimation results should be at "Saving output results to "results/output/zen_talking_phone/vibe_output.pkl"". Looks like your pyrender is throwing errors?

**Comment by melih1996** [comment]
Is it like a version incompatibility of pyrenderer?
